# Generated by Django 6.0.7 on 2026-07-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_text',
            field=models.TextField(blank=True, help_text='Extracted CV text for AI analysis'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
